import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${inter.variable} antialiased font-inter`}>
        <header>
          <nav className="bg-base-100 shadow-sm">
            <Navbar />
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
